
spring:
  cloud:
    aws:
      s3:
        endpoint: http://s3.localhost.localstack.cloud:4566
        region: us-east-1
      credentials:
        access-key: none
        secret-key: none
      region:
        static: us-east-1


